version: '3.9'

services:
  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    environment:
      - UID=1000
      - GID=1000
      - NODE_ENV=production
    volumes:
      - /data/dashy/my-local-conf.yml:/app/public/conf.yml
      - /data/dashy/item-icons:/app/public/item-icons
    ports:
      - 4000:80
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s